build: false
version: 1.0.{build}

branches:
    only:
        - master

install:
    - call "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat"

    - git submodule update --init --recursive

    - set "ABSPATH=%cd%\.."
    - set "SCRIPTPATH=%cd%"
    - set "SRCPATH=%ABSPATH%"
    - set "SYSROOTPATH=%ABSPATH%\sysroot"
    - set "LIBPATH=%ABSPATH%\lib\\"
    - set "INCLUDEPATH=%ABSPATH%\include\\"

    - mkdir "%SYSROOTPATH%\usr"

    - set "SYSROOT=%SYSROOTPATH%"
    - set "BUILDPATH=%SCRIPTPATH%\build"
    - mkdir "%BUILDPATH%"

    - mkdir "%BUILDPATH%\libcorrect"
    - cd "%BUILDPATH%\libcorrect"
    - cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX="%SYSROOT%\usr" -G "Visual Studio 14 2015 Win64" "%SRCPATH%\libcorrect"
    - cmake --build . --config Release --target shim
    - cmake --install .

    - mkdir "%BUILDPATH%/liquid-dsp"
    - cd "%BUILDPATH%/liquid-dsp"
    - cmake -DCMAKE_BUILD_TYPE=Release "%SRCPATH%/liquid-dsp" -DCMAKE_INSTALL_PREFIX="%SYSROOT%/usr"  -DCMAKE_PREFIX_PATH="%SYSROOT%" -DCMAKE_SHARED_LINKER_FLAGS="/LIBPATH %SYSROOT%/usr/lib" -DLIQUID_BUILD_EXAMPLES="off" -DLIQUID_BUILD_SANDBOX="off" -G "Visual Studio 14 2015 Win64"
    - cmake --build . --config Release --target liquid-static
    - cmake --install .

    - cd ../../jansson
    - mkdir build
    - cd build
    - cmake -DCMAKE_BUILD_TYPE=Release -DJANSSON_BUILD_SHARED_LIBS=off -DJANSSON_WITHOUT_TESTS=on -DJANSSON_EXAMPLES=off -DJANSSON_BUILD_DOCS=off -G "Visual Studio 14 2015 Win64" ..
    - cmake --build . --config Release

    - cd ../../portaudio
    - mkdir cmake_build
    - cd cmake_build
    - cmake -G "Visual Studio 14 2015 Win64" ..
    - cmake --build . --config Release
