build: false
version: '{build}'

branches:
    only:
        - master

environment:
    matrix:
        - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
          COMPILER: cl.exe
          MSVC_BAT: C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat
          MSVC_BAT_ARCH: x86
          GENERATOR: "Visual Studio 14 2015 Win64"
          APPVEYOR_SAVE_CACHE_ON_ERROR: true

before_build:
    - if DEFINED MSVC_BAT call "%MSVC_BAT%" %MSVC_BAT_ARCH%
    - cd %APPVEYOR_BUILD_FOLDER%

build_script:
    - git submodule update --init --recursive

    - cd scripts
    - set "ABSPATH=%cd%\.."
    - set "SCRIPTPATH=%cd%"
    - set "SRCPATH=%ABSPATH%"
    - set "SYSROOTPATH=%SCRIPTPATH%/build\sysroot"

    - mkdir "%SYSROOTPATH%/usr"

    - set "BUILDPATH=%SCRIPTPATH%/build"

    - mkdir "%BUILDPATH%\libcorrect"
    - cd "%BUILDPATH%\libcorrect"
    - cmake -G "%GENERATOR%" -DCMAKE_C_COMPILER=%COMPILER% -DCMAKE_CXX_COMPILER=%COMPILER% -DCMAKE_BUILD_TYPE=Release "%SRCPATH%/libcorrect" -DCMAKE_INSTALL_PREFIX="%SYSROOTPATH%/usr"
    - cmake --build . --config Release --target shim
    - cmake --build . --config Release --target install

    - mkdir "%BUILDPATH%/liquid-dsp"
    - cd "%BUILDPATH%/liquid-dsp"
    - cmake -G "%GENERATOR%" -DCMAKE_C_COMPILER=%COMPILER% -DCMAKE_CXX_COMPILER=%COMPILER% -DCMAKE_BUILD_TYPE=Release "%SRCPATH%/liquid-dsp" -DCMAKE_INSTALL_PREFIX="%SYSROOTPATH%/usr" -DCMAKE_PREFIX_PATH="%SYSROOTPATH%" -DLIQUID_BUILD_EXAMPLES="off" -DLIQUID_BUILD_SANDBOX="off"
    - cmake --build . --config Release --target liquid-static
    - cmake --build . --config Release --target install

    - mkdir "%BUILDPATH%/jansson"
    - cd "%BUILDPATH%/jansson"
    - cmake -G "%GENERATOR%" -DCMAKE_C_COMPILER=%COMPILER% -DCMAKE_CXX_COMPILER=%COMPILER% -DCMAKE_BUILD_TYPE=Release "%SRCPATH%/jansson" -DCMAKE_INSTALL_PREFIX="%SYSROOTPATH%/usr" -DJANSSON_BUILD_SHARED_LIBS=off -DJANSSON_WITHOUT_TESTS=on -DJANSSON_EXAMPLES=off -DJANSSON_BUILD_DOCS=off
    - cmake --build . --config Release
    - cmake --build . --config Release --target install

    - mkdir "%BUILDPATH%/portaudio"
    - cd "%BUILDPATH%/portaudio"
    - cmake -G "%GENERATOR%" -DCMAKE_C_COMPILER=%COMPILER% -DCMAKE_CXX_COMPILER=%COMPILER% -DCMAKE_BUILD_TYPE=Release "%SRCPATH%/portaudio" -DCMAKE_INSTALL_PREFIX="%SYSROOTPATH%/usr"
    - cmake --build . --config Release
    - cp "%SRCPATH%/portaudio/include/portaudio.h" "%SYSROOTPATH%/usr/include/portaudio.h"
    - cp "%BUILDPATH%/portaudio/Release/portaudio_static_x64.lib" "%SYSROOTPATH%/usr/lib/portaudio.lib"
    - cp "%BUILDPATH%/portaudio/Release/portaudio_x64.dll" "%SYSROOTPATH%/usr/lib/portaudio.dll"

    - cd "%SYSROOTPATH%/usr"
    - dir /s

    - mkdir "%BUILDPATH%/libquiet"
    - cd "%BUILDPATH%/libquiet"
    - cmake -G "%GENERATOR%" -DCMAKE_C_COMPILER=%COMPILER% -DCMAKE_CXX_COMPILER=%COMPILER% -DCMAKE_BUILD_TYPE=Release "%SRCPATH%/libquiet" -DCMAKE_INSTALL_PREFIX="%SYSROOTPATH%/usr" -DQUIET_CXX=on
    - cmake --build . --config Release

    - set "LIBDESTPATH=%ABSPATH%/lib/"
    - set "INCLUDEDESTPATH=%ABSPATH%/include/"
